import {StyleSheet} from 'react-native';
import {windowHeight, windowWidth} from '../../utils/dimensions';

const stylesEditForm = StyleSheet.create({
  containerModalEdit: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    height: windowHeight,
    width: windowWidth,
    zIndex: 0,
    elevation: 0,
  },
  formContainer: {
    backgroundColor: '#F2F2F2',
    borderRadius: 30,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 24,
    position: 'relative',
    minHeight: windowHeight / 2,
    width: windowWidth - 32,
  },
  leaveButton: {
    fontSize: 17,
    color: '#000000',
    fontWeight: '500',
    alignSelf: 'flex-start',
  },
  saveButton: {
    fontSize: 17,
    color: '#000000',
    fontWeight: '500',
    alignSelf: 'flex-end',
  },
  containerAvatarUser: {
    width: 120,
    height: 120,
    borderRadius: 120,
    position: 'relative',
    top: -105,
    left: '32%',
    backgroundColor: '#FFFFFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarUser: {
    width: 102,
    height: 102,
    borderRadius: 102,
    backgroundColor: 'rgb(185, 212, 219)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    resizeMode: 'cover',
  },
  controlForm: {
    marginTop: 28,
  },
  optionForm: {
    marginTop: 25,
  },
  buttonOption: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingLeft: 20,
    paddingRight: 20,
    height: 44,
  },
  buttonOptionText: {
    color: '#000000',
    fontSize: 15,
    alignSelf: 'flex-start',
    paddingLeft: 15,
  },
  uploadAvatarUser: {
    position: 'absolute',
    top: 85,
    left: 85,
  },
  opacityText: {
    opacity: 0.2,
  },
  toastMessageView: {
    zIndex: 2,
    elevation: 2,
    width: windowWidth - 32,
    height: 58,
    borderRadius: 16,
  },
  textToastMessage: {
    color: '#fff',
    fontSize: 15,
    paddingLeft: 10,
    alignSelf: 'flex-start',
  },
  textGroup: {
    width: windowWidth - 32,
    height: 58,
    zIndex: 2,
    elevation: 2,
    paddingRight: 18,
    paddingLeft: 18,
  },
  toastErrorMessageContainer: {
    backgroundColor: 'red',
    color: '#fff',
  },
  groupAvatar: {
    height: '14%',
  },
  containUserProfile: {
    zIndex: 1,
    elevation: 1,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    width: windowWidth,
    marginBottom: 24,
    paddingLeft: 16,
    paddingRight: 16,
    paddingVertical: 16,
  },
  btnConfirm: {
    width: '100%',
    height: 44,
    marginTop: 24,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#50429B',
  },
  textConfirm: {
    fontSize: 20,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '700',
    fontFamily: 'Nunito',
  },
  activeBtnConfirm: {
    backgroundColor: '#A5ABDE',
  },
  textChangePassword: {
    fontSize: 17,
    lineHeight: 23,
    marginLeft: 14,
    color: '#000000',
    fontWeight: '500',
    fontFamily: 'Nunito',
  },
});

export default stylesEditForm;
